version: '3.8'

services:
  # Laravel Application (Development)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: aplikasi-madiun-dev
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_HOST=mysql
      - DB_DATABASE=aplikasi_madiun_dev
      - DB_USERNAME=dev_user
      - DB_PASSWORD=dev_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - /var/www/html/vendor
      - /var/www/html/node_modules
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - dev-network

  # MySQL Database (Development)
  mysql:
    image: mysql:8.0
    container_name: aplikasi-madiun-mysql-dev
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=aplikasi_madiun_dev
      - MYSQL_USER=dev_user
      - MYSQL_PASSWORD=dev_password
    volumes:
      - mysql-dev-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  # Redis Cache (Development)
  redis:
    image: redis:7-alpine
    container_name: aplikasi-madiun-redis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-dev-data:/data
    ports:
      - "6380:6379"
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  # MailHog for email testing
  mailhog:
    image: mailhog/mailhog:latest
    container_name: aplikasi-madiun-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - dev-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: aplikasi-madiun-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=dev_user
      - PMA_PASSWORD=dev_password
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - dev-network

  # Redis Commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: aplikasi-madiun-redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - dev-network

volumes:
  mysql-dev-data:
    driver: local
  redis-dev-data:
    driver: local

networks:
  dev-network:
    driver: bridge
