apiVersion: v1
kind: Namespace
metadata:
  name: aplikasi-madiun
  labels:
    name: aplikasi-madiun
    environment: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: aplikasi-madiun
data:
  APP_NAME: "Aplikasi Data Aplikasi Kabupaten Madiun"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://apps.madiunkab.go.id"
  LOG_CHANNEL: "stderr"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "error"
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "redis"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "redis"
  SESSION_DRIVER: "redis"
  SESSION_LIFETIME: "120"
  REDIS_HOST: "redis-service"
  REDIS_PASSWORD: ""
  REDIS_PORT: "6379"
  MAIL_MAILER: "smtp"
  MAIL_HOST: "mailpit"
  MAIL_PORT: "1025"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  MAIL_ENCRYPTION: ""
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "Aplikasi Madiun"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: aplikasi-madiun
type: Opaque
data:
  # Base64 encoded values - ganti dengan nilai actual
  DB_DATABASE: YXBsaWthc2lfbWFkaXVu  # aplikasi_madiun
  DB_USERNAME: bWFkaXVuX3VzZXI=      # madiun_user
  DB_PASSWORD: c2VjcmV0UGFzcw==      # secretPass
  APP_KEY: YmFzZTY0OktleUhlcmU=      # base64:KeyHere
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplikasi-madiun-app
  namespace: aplikasi-madiun
  labels:
    app: aplikasi-madiun
    tier: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: aplikasi-madiun
      tier: frontend
  template:
    metadata:
      labels:
        app: aplikasi-madiun
        tier: frontend
    spec:
      containers:
      - name: aplikasi-madiun
        image: aplikasi-madiun:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: APP_KEY
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: storage-volume
          mountPath: /var/www/html/storage/app
        - name: logs-volume
          mountPath: /var/www/html/storage/logs
      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: app-storage-pvc
      - name: logs-volume
        emptyDir: {}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: aplikasi-madiun-service
  namespace: aplikasi-madiun
  labels:
    app: aplikasi-madiun
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: aplikasi-madiun
    tier: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-storage-pvc
  namespace: aplikasi-madiun
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storage  # Sesuaikan dengan storage class yang tersedia
