apiVersion: batch/v1
kind: Job
metadata:
  name: aplikasi-madiun-migrate
  namespace: aplikasi-madiun
  labels:
    app: aplikasi-madiun
    type: migration
spec:
  template:
    metadata:
      labels:
        app: aplikasi-madiun
        type: migration
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migrate
        image: aplikasi-madiun:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "Waiting for database to be ready..."
          until php artisan migrate:status; do
            echo "Database not ready, waiting..."
            sleep 5
          done
          echo "Running migrations..."
          php artisan migrate --force
          echo "Migrations completed!"
        env:
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: APP_KEY
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DB_PASSWORD
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aplikasi-madiun-backup
  namespace: aplikasi-madiun
  labels:
    app: aplikasi-madiun
    type: backup
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: aplikasi-madiun
            type: backup
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: aplikasi-madiun:latest
            command: ["/bin/sh"]
            args:
            - -c
            - |
              echo "Starting backup process..."
              php artisan backup:aplikasis
              echo "Backup completed!"
            env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: APP_KEY
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            envFrom:
            - configMapRef:
                name: app-config
            volumeMounts:
            - name: backup-storage
              mountPath: /var/www/html/storage/app/backups
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: aplikasi-madiun
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-storage
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: aplikasi-madiun-scheduler
  namespace: aplikasi-madiun
  labels:
    app: aplikasi-madiun
    type: scheduler
spec:
  schedule: "* * * * *"  # Every minute
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: aplikasi-madiun
            type: scheduler
        spec:
          restartPolicy: OnFailure
          containers:
          - name: scheduler
            image: aplikasi-madiun:latest
            command: ["/bin/sh"]
            args:
            - -c
            - |
              php artisan schedule:run --verbose --no-interaction
            env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: APP_KEY
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            envFrom:
            - configMapRef:
                name: app-config
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
