apiVersion: v1
kind: Service
metadata:
  name: aplikasi-madiun-monitoring
  namespace: aplikasi-madiun
  labels:
    app: aplikasi-madiun
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: aplikasi-madiun
    tier: frontend
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aplikasi-madiun-metrics
  namespace: aplikasi-madiun
  labels:
    app: aplikasi-madiun
spec:
  selector:
    matchLabels:
      app: aplikasi-madiun
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: aplikasi-madiun-alerts
  namespace: aplikasi-madiun
  labels:
    app: aplikasi-madiun
spec:
  groups:
  - name: aplikasi-madiun.rules
    rules:
    - alert: AplikasiMadiunDown
      expr: up{job="aplikasi-madiun-monitoring"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Aplikasi Madiun is down"
        description: "Aplikasi Madiun has been down for more than 5 minutes."
    
    - alert: AplikasiMadiunHighCPU
      expr: rate(container_cpu_usage_seconds_total{pod=~"aplikasi-madiun-app-.*"}[5m]) > 0.8
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage on Aplikasi Madiun"
        description: "CPU usage is above 80% for more than 10 minutes."
    
    - alert: AplikasiMadiunHighMemory
      expr: container_memory_usage_bytes{pod=~"aplikasi-madiun-app-.*"} / container_spec_memory_limit_bytes > 0.9
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage on Aplikasi Madiun"
        description: "Memory usage is above 90% for more than 5 minutes."
    
    - alert: AplikasiMadiunResponseTime
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="aplikasi-madiun-monitoring"}[5m])) > 2
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High response time on Aplikasi Madiun"
        description: "95th percentile response time is above 2 seconds for more than 10 minutes."
    
    - alert: MySQLDown
      expr: up{job="mysql-service"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "MySQL is down"
        description: "MySQL database has been down for more than 2 minutes."
    
    - alert: RedisDown
      expr: up{job="redis-service"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Redis is down"
        description: "Redis cache has been down for more than 2 minutes."
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard
  namespace: aplikasi-madiun
  labels:
    grafana_dashboard: "1"
data:
  aplikasi-madiun-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Aplikasi Data Aplikasi Kabupaten Madiun",
        "tags": ["kubernetes", "laravel", "aplikasi-madiun"],
        "style": "dark",
        "timezone": "Asia/Jakarta",
        "panels": [
          {
            "id": 1,
            "title": "Application Status",
            "type": "stat",
            "targets": [
              {
                "expr": "up{job=\"aplikasi-madiun-monitoring\"}",
                "legendFormat": "Application Status"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "thresholds"
                },
                "thresholds": {
                  "steps": [
                    {"color": "red", "value": 0},
                    {"color": "green", "value": 1}
                  ]
                },
                "mappings": [
                  {"options": {"0": {"text": "DOWN"}}, "type": "value"},
                  {"options": {"1": {"text": "UP"}}, "type": "value"}
                ]
              }
            },
            "gridPos": {"h": 4, "w": 6, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Request Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(http_requests_total{job=\"aplikasi-madiun-monitoring\"}[5m])",
                "legendFormat": "Requests/sec"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 6, "y": 0}
          },
          {
            "id": 3,
            "title": "Response Time",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job=\"aplikasi-madiun-monitoring\"}[5m]))",
                "legendFormat": "95th percentile"
              },
              {
                "expr": "histogram_quantile(0.50, rate(http_request_duration_seconds_bucket{job=\"aplikasi-madiun-monitoring\"}[5m]))",
                "legendFormat": "50th percentile"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 18, "y": 0}
          },
          {
            "id": 4,
            "title": "Pod CPU Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(container_cpu_usage_seconds_total{pod=~\"aplikasi-madiun-app-.*\"}[5m])",
                "legendFormat": "{{pod}}"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 8}
          },
          {
            "id": 5,
            "title": "Pod Memory Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "container_memory_usage_bytes{pod=~\"aplikasi-madiun-app-.*\"} / 1024 / 1024",
                "legendFormat": "{{pod}}"
              }
            ],
            "yAxes": [
              {"unit": "MB"},
              {"unit": "short"}
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 8}
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s"
      }
    }
